#!/bin/bash
CURDIR='.conf'
ln -s $CURDIR/bash_profile ~/.bash_profile
ln -s $CURDIR/bashrc ~/.bashrc
ln -s $CURDIR/gitconfig ~/.gitconfig
ln -s $CURDIR/ssh ~/.ssh
ln -s $CURDIR/vimrc ~/.vimrc
ln -s $CURDIR/vim ~/.vim
